### ISSUE TITLE
Works correctly for only 3 elements

### ISSUE THREAD

**Issue by deresegetachew** [chagasaway/react-native-fading-slides#1]
I had 5 children for my carousel but its not working properly past page 3

**Comment by chagasaway** [comment]
Hi @derese, thanks for reporting this issue.

I will take a look at it on this weekend to find the possible cause for this kind of problem.

**Comment by deresegetachew** [comment]
Sorry had a lot of tabs opened and wrote it here by mistake i was referring to https://github.com/roscoe054/fastui-carousel
